### ISSUE TITLE
Laravel v9 Support?

### ISSUE THREAD

**Issue by BrekiTomasson** [adrianorsouza/laravel-geolocation#2]
Any plans on updating this to support Laravel v9? It's one of very few packages that are holding me back from updating my framework.

**Comment by BrekiTomasson** [comment]
Ping @adrianorsouza

**Comment by adrianorsouza** [comment]
@BrekiTomasson yes we do very soon, anyhow PR are welcome.

**Comment by BrekiTomasson** [comment]
It's been a month. Any news?

**Comment by BrekiTomasson** [comment]
It's been **two** months. Any news?

**Comment by adrianorsouza** [comment]
Hey @BrekiTomasson, I'm aware of the need to this update. But please try to contribute open source projects that is relevant to you instead of keep waiting and putting pressure to the authors to make updates for you, that's why open source community is all about.

**Comment by BrekiTomasson** [comment]
Done. See #3 for details.
