### ISSUE TITLE
array_key_exists() in production

### ISSUE THREAD

**Issue by SyahrulRomadoni** [adrianorsouza/laravel-geolocation#4]
I just installed the geolocation package. When I run it locally, it runs fine, but when it's in production, geolocation suddenly becomes an error with the following text "array_key_exists(): Argument #2 ($array) must be of type array, string given ", what is the reason for this?

this is an example of my coding:

```
        $check_location = GeoLocation::lookup($_SERVER['REMOTE_ADDR']);
        $model = new Pengunjung();
        $model_check = Pengunjung::where('ip', $check_location->getIp())->whereDate('created_at', date('Y-m-d'))->first();
        if ($model_check == null) {
            $model->ip = $check_location->getIp();
            $model->city = $check_location->getCity();
            $model->region = $check_location->getRegion();
            $model->country = $check_location->getCountry();
            $model->latitude = $check_location->getLatitude();
            $model->longitude = $check_location->getLongitude();
            $model->save();
        }
```

**Comment by adrianorsouza** [comment]
Hey @SyahrulRomadoni at first it does not seem to be an issue related to this package, please try to debug `$_SERVER['REMOTE_ADDR']` the model itself.

**Comment by tchavetdeuse** [comment]
Hi, I got the problem as well, it did come from the package (line 183 in GeoLocationDetails.php). In my case it happened when I called getCountry() while in a locale other than English. I guess the trans method on line 181 couldn't find the translation for 'geolocation::countries" and didn't use English as fallback. The solution was to run `php artisan vendor:publish --tag=geolocation-translations` then copy the folder resources/lang/vendor/geolocation/en for other locales

**Comment by adrianorsouza** [comment]
@tchavetdeuse could you please gives us a way to reproduce it?

I'm kinda concerned if laravel 10 lang removal has something to do with this.

**Comment by tchavetdeuse** [comment]
I'm using laravel 8. I have locale and fallback_locale set to fr in config/app.php
I was able to reproduce the issue by creating a new project, setting locale and fallback_locale to fr in config/app.php then simply trying to display the country in the example view: 
routes/web.php
```php
<?php

use Illuminate\Support\Facades\Route;
use Adrianorosa\GeoLocation\GeoLocation;

Route::get('/', function () {
    $details = GeoLocation::lookup('8.8.8.8');
    return view("welcome", ["country" => $details->getCountry()]);
});
```
Then somewhere in ressources/views/welcome.blade.php:
`{{$country}}`

**Comment by adrianorsouza** [comment]
@tchavetdeuse it seems to me that we're not assuming a fallback locale other than `en` or `pt_BR`, I'll give it a try in this scenario you've reported above and try to find what's happening there, keep you guys posted.
